default_context:
  project_name: 'fapi'
  project_slug: 'fapi'
  domain_main: 'fapi.com'
  domain_staging: 'stag.fapi.com'
  docker_swarm_stack_name_main: 'fapi-com'
  docker_swarm_stack_name_staging: 'stag-fapi-com'
  secret_key: 'c1b14c2ec64b2e69614392ec0e82d17e'
  first_superuser: 'admin@fapi.com'
  first_superuser_password: 'c1b14c2ec64b2e69614392ec0e82d17e'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.fapi.com", "https://stag.fapi.com", "https://fapi.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@fapi.com'
  postgres_password: 'c1b14c2ec64b2e69614392ec0e82d17e'
  pgadmin_default_user: 'admin@fapi.com'
  pgadmin_default_user_password: 'c1b14c2ec64b2e69614392ec0e82d17e'
  traefik_constraint_tag: 'fapi.com'
  traefik_constraint_tag_staging: 'stag.fapi.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:c1b14c2ec64b2e69614392ec0e82d17e'
  sentry_dsn: ''
  docker_image_prefix: 'fapi_'
  docker_image_backend: 'fapi_backend'
  docker_image_celeryworker: 'fapi_celeryworker'
  docker_image_frontend: 'fapi_frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
